early ispc support.

diff --git a/ipmacc b/ipmacc
--- a/ipmacc
+++ b/ipmacc
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VERSION=0.8.4b
+VERSION=0.8.5b
 function usage()
 {
     echo "    IPMACC version $VERSION, Copyright (C) 2015 Ahmad Lashgar"
@@ -14,6 +14,8 @@ function usage()
     echo "other useful inlines:"
     echo " ipmacc --help"
     echo "   see this message."
+    echo " ipmacc --list-backends"
+    echo "   list backends which IPMACC is compiled for."
     echo " ipmacc --list-devices OCL"
     echo "   list available OpenCL devices."
     echo " ipmacc --list-devices CUDA"
@@ -72,18 +74,28 @@ elif [ "$ta" == "nvopencl" ] ; then
     if [ "$OPENCLSUPPORT" != "1" ] ; then
         echo 'warning: targeting for nvopencl while the environemnt is not setup for OpenCL'
     fi
+elif [ "$ta" == "intelispc" ] ; then
+    TARGETARCH="intelispc"
+    if [ "$ISPCSUPPORT" != "1" ] ; then
+        echo 'warning: targeting for intelispc while the environemnt is not setup for ISPC'
+    fi
 else
     #fallback
-    if [ "$CUDASUPPORT" != "1" ] ; then
+    if [ "$CUDASUPPORT" == "1" ] ; then
         if [ "$VERBOSE" == "1" ] ; then
-         echo "falling back to CUDA target"
+         echo "target unspecified: falling back to CUDA target"
         fi
         TARGETARCH="nvcuda"
-    elif [ "$OPENCLSUPPORT" != "1" ] ; then
+    elif [ "$OPENCLSUPPORT" == "1" ] ; then
         if [ "$VERBOSE" == "1" ] ; then
-         echo "falling back to OpenCL target"
+         echo "target unspecified: falling back to OpenCL target"
         fi
         TARGETARCH="nvopencl"
+    elif [ "$ISPCSUPPORT" == "1" ] ; then
+        if [ "$VERBOSE" == "1" ] ; then
+         echo "target unspecified: falling back to ISPC target"
+        fi
+        TARGETARCH="intelispc"
     else
         echo 'fatal error! unable to find an enabled backend. enable CUDASUPPORT or OPENCLSUPPORT in setup_environment file.'
         exit
@@ -101,26 +113,28 @@ NVCCARGS=
 OPTIMIZATION= #optimization swtiches
 for (( i = 0 ; i < $NARG ; i++ )) ; do
     # check for pending args
-    if [ "$tapending" == "1" ] ; then
+    if [ "$pendingta" == "1" ] ; then
         ta=${ARGS[i]}
-        tapending="0"
+        pendingta="0"
         continue
-    elif [ "$accfilepending" == "1" ] ; then
+    elif [ "$pendingaccfile" == "1" ] ; then
         INFILE=${ARGS[i]}
-        accfilepending="0"
+        pendingaccfile="0"
         continue
-    elif [ "$optimizationpending" == "1" ] ; then
+    elif [ "$pendingoptimization" == "1" ] ; then
         OPTIMIZATION=${ARGS[i]}
-        optimizationpending="0"
+        pendingoptimization="0"
         continue
     fi
 
-    # pars new arg
+    # parse new arg
     if [ "${ARGS[i]}" == "--cflags" ] ; then
         if [ $TARGETARCH == "nvcuda" ] ; then
             echo -D__NVCUDA__ $CFLAG
         elif [ $TARGETARCH == "nvopencl" ] ; then
             echo -D__NVOPENCL__ $CFLAG
+        elif [ $TARGETARCH == "intelispc" ] ; then
+            echo -D__INTELISPC__ $CFLAG
         fi
         exit 1
     elif [ "${ARGS[i]}" == "--ldflags" ] ; then
@@ -129,19 +143,36 @@ for (( i = 0 ; i < $NARG ; i++ )) ; do
     elif [ "${ARGS[i]}" == "-h" ] || [ "${ARGS[i]}" == "--help" ] ; then
         usage
         exit 1
-    elif [ "${ARGS[i]}" == "-h" ] || [ "${ARGS[i]}" == "--list-devices" ] ; then
+    elif [ "${ARGS[i]}" == "--list-devices" ] ; then
         $path/src/listdevices ${ARGS[i+1]}
+        exit 1
+    elif [ "${ARGS[i]}" == "--list-backends" ] ; then
+        if [ "$CUDASUPPORT" == "1" ] ; then
+            echo 'CUDA backend   [Enabled ]'
+        else
+            echo 'CUDA backend   [Disabled]'
+        fi
+        if [ "$OPENCLSUPPORT" == "1" ] ; then
+            echo 'OpenCL backend [Enabled ]'
+        else
+            echo 'OpenCL backend [Disabled]'
+        fi
+        if [ "$ISPCSUPPORT" == "1" ] ; then
+            echo 'ISPC backend   [Enabled ]'
+        else
+            echo 'ISPC backend   [Disabled]'
+        fi
         exit 1
     elif [ "${ARGS[i]}" == "--version" ] ; then
     #elif [ "${ARGS[i]}" == "-v" ] || [ "${ARGS[i]}" == "--version" ] ; then
         version
         exit 1
     elif [ "${ARGS[i]}" == "--ta" ] ; then
-        tapending="1"
+        pendingta="1"
     elif [ "${ARGS[i]}" == "--accfile" ] ; then
-        accfilepending="1"
+        pendingaccfile="1"
     elif [ "${ARGS[i]}" == "--enable" ] ; then
-        optimizationpending="1"
+        pendingoptimization="1"
     elif [ "$i" != "0" ] ; then
         # append this arg
         NVCCARGS="${NVCCARGS} ${ARGS[i]}"
@@ -171,6 +202,16 @@ if [ ! -f "$NVCC" ] && [ "$TARGETARCH" == "nvcuda" ] ; then
     echo "exiting with failure"
     exit 1
 fi
+# Path to ispc
+ISPC=${ISPCHOME}/ispc
+if [ ! -f "$ISPC" ] && [ "$TARGETARCH" == "intelispc" ] ; then
+    echo "unable to locate ispc"
+    echo "potentially, environment variables are not properly set!"
+    echo "check the README file for installation and setup"
+    echo "exiting with failure"
+    exit 1
+fi
+
 # System C/C++ Compiler
 CC=gcc
 CXX=g++
@@ -191,6 +232,8 @@ if [ "$TARGETARCH" == "nvcuda" ] ; then
     OUTPUT=`echo "$INFILE " | sed -r 's/(\.cu\ )/_ipmacc\.cu/g' | sed -r 's/(\.[cC]\ )/_ipmacc\.cu/g' | sed -r 's/(\.cpp\ )/_ipmacc\.cu/g' `
 else 
     OUTPUT=`echo "$INFILE " | sed -r 's/(\.[cC]\ )/_ipmacc\.c/g' | sed -r 's/(\.cpp\ )/_ipmacc\.cpp/g' `
+    ISPCKERNEL=`echo "$INFILE " | sed -r 's/(\.[cC]\ )/_ipmacc\.ispc/g' | sed -r 's/(\.cpp\ )/_ipmacc\.ispc/g' `
+    ISPCKERNELOBJ=`echo "$INFILE " | sed -r 's/(\.[cC]\ )/_ipmacc\.o/g' | sed -r 's/(\.cpp\ )/_ipmacc\.o/g' `
 fi
 
 # RUN IPMACC
@@ -229,7 +272,7 @@ if [ "$?" == "0" ] ; then
                 echo "[failed] nvcc failed to generate the binary"
             fi
         elif [ $TARGETARCH == "nvopencl" ] ; then
-            # 5. Call CC to compile the CUDA
+            # 5. Call CC to compile the OpenCL
             if [ "$VERBOSE" == "1" ] ; then
              echo -en "\n=============$CXX LOGS==============\n"
              echo "$CXX $CFLAG $LDFLAG $NVCCARGS $OUTPUT -D__NVOPENCL__"
@@ -238,6 +281,27 @@ if [ "$?" == "0" ] ; then
             if [ "$?" != "0" ] ; then
                 echo "[failed] $CXX failed to generate the binary"
             fi
+        elif [ "$TARGETARCH" == "intelispc" ] ; then
+            # 5. Call ISPC to compile the ISPC kernel
+            if [ "$VERBOSE" == "1" ] ; then
+             echo -en "\n=============ISPC LOGS==============\n"
+             echo "$ISPC $ISPCFLAG $ISPCKERNEL -D__INTELISPC__ -o $ISPCKERNELOBJ"
+            fi
+            #echo "$NVCC $CFLAG $LDFLAG $NVCCARGS $OUTPUT -D__NVCUDA__"
+            $ISPC $ISPCFLAG $ISPCKERNEL -D__INTELISPC__ -o $ISPCKERNELOBJ
+            if [ "$?" != "0" ] ; then
+                echo "[failed] ispc failed to generate the object code"
+            fi
+            # 5. CC to compile the compile host and link
+            if [ "$VERBOSE" == "1" ] ; then
+             echo -en "\n=============$CXX LOGS==============\n"
+             echo "$CXX $CFLAG $LDFLAG $OUTPUT -D__INTELISPC__ $ISPCKERNELOBJ $NVCCARGS"
+            fi
+            $CXX $CFLAG $LDFLAG $OUTPUT -D__INTELISPC__ $ISPCKERNELOBJ $NVCCARGS
+            if [ "$?" != "0" ] ; then
+                echo "[failed] $CXX failed to generate the binary"
+            fi
+
         fi
     fi
     rm $OUTPUT~ -f #cleaning GNU indent
